# Generated by Django 4.2.4 on 2023-08-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adherence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accounts',
            table='accounts',
        ),
        migrations.AlterModelTable(
            name='assets',
            table='assets',
        ),
        migrations.AlterModelTable(
            name='clients',
            table='clients',
        ),
    ]
